#!/usr/bin/env python3
"""Regenerates ecg-demo-alt.safetensors, the committed demonstrator weight file.

The .safetensors beside this script is a committed *source asset*, exactly like the .spv files
under recipes/shader/ - it is not produced by the build, and the build never runs this script.
That is the same reasoning ADR-007 gives for committing SPIR-V: an artifact whose bytes depend on
whichever version of a generator the CI image happens to ship is not byte-reproducible.

## These weights are synthetic. They are not trained on anything.

Every value below comes from the linear congruential generator in this file. No ECG data, no
clinical data, and no data of any kind was involved in producing them. The model they parameterise
classifies nothing: its outputs are a deterministic function of its inputs with no learned meaning
whatsoever.

They exist so that the pipeline - import, validate, bake, embed, self-test, predict - can be
demonstrated end to end on a committed artifact, and so that issue #64's weight-swap test can prove
that replacing them requires no application source change. Substituting a manufacturer's own
qualified weights is a re-bake of this recipe against a different file.

**Nothing here has any clinical validity and none is claimed.** See ADR-008.

## Why an LCG rather than numpy

Reproducibility without a dependency, and the same reason the golden generator avoids <random>:
the sequence has to be determined by this file alone, so that anyone can regenerate a byte-identical
asset from it. Xavier-style scaling keeps the activations in a sensible range so the demonstrator's
softmax output is not saturated - it is cosmetic, not meaningful.

Usage:
    python3 recipes/model/ecg-demo/generate-demonstrator-weights.py
    cmake --build <build-dir> --target mdux-bake-update    # then review the diff
"""

import json
import struct
from pathlib import Path

MASK = 0xFFFFFFFF


class Lcg:
    """The generator named lcg-numerical-recipes-32, matching tools/ml/GoldenGen.cpp."""

    def __init__(self, seed: int) -> None:
        self.state = seed & MASK

    def next_u32(self) -> int:
        self.state = (self.state * 1664525 + 1013904223) & MASK
        return self.state

    def next_unit(self) -> float:
        """A value in [-1, 1), exactly representable in f32 (division by a power of two)."""
        return (self.next_u32() >> 8) / 8388608.0 - 1.0


def draw(rng: Lcg, count: int, scale: float) -> list[float]:
    """`count` values in [-scale, scale), rounded through f32 so the file holds what we computed."""
    values = []
    for _ in range(count):
        value = rng.next_unit() * scale
        # Round-trip through f32 so the Python double and the stored float agree exactly.
        values.append(struct.unpack("<f", struct.pack("<f", value))[0])
    return values


def main() -> None:
    rng = Lcg(19700101)

    # The demonstrator architecture (issue #64), which exercises every v1 kernel:
    #   180 x 1 -> Conv1D k=9 s=1, 8 filters, relu -> 172 x 8
    #           -> MaxPool1D k=4 s=4               ->  43 x 8
    #           -> Conv1D k=5 s=1, 16 filters, relu ->  39 x 16
    #           -> Flatten                          -> 624
    #           -> Dense 624 -> 4, softmax          ->   4
    #
    # Scales are 1/sqrt(fan_in), which keeps activations off both rails. Biases are zero: a
    # demonstrator gains nothing from arbitrary offsets, and zero is the one value that needs no
    # explanation.
    tensors = {
        "conv1.weight": (draw(rng, 8 * 1 * 9, 1.0 / (9 ** 0.5)), [8, 1, 9]),
        "conv1.bias": ([0.0] * 8, [8]),
        "conv2.weight": (draw(rng, 16 * 8 * 5, 1.0 / (40 ** 0.5)), [16, 8, 5]),
        "conv2.bias": ([0.0] * 16, [16]),
        "dense.weight": (draw(rng, 4 * 624, 1.0 / (624 ** 0.5)), [4, 624]),
        "dense.bias": ([0.0] * 4, [4]),
    }

    # Tensors are laid out in sorted-name order so this script is itself deterministic. The baker
    # repacks them in layer order regardless, so this ordering does not reach package.json.
    header: dict[str, object] = {}
    payload = bytearray()
    for name in sorted(tensors):
        values, shape = tensors[name]
        begin = len(payload)
        for value in values:
            payload += struct.pack("<f", value)
        header[name] = {
            "dtype": "F32",
            "shape": shape,
            "data_offsets": [begin, len(payload)],
        }

    header["__metadata__"] = {
        "provenance": "synthetic, generated by generate-demonstrator-weights.py",
        "training_data": "none - these weights are not trained",
        "clinical_validity": "none - demonstrator only, not for any clinical use",
        "generator": "lcg-numerical-recipes-32",
        "seed": "19700101",
    }

    # Compact separators and sorted keys, so the header bytes depend only on the content.
    header_bytes = json.dumps(header, sort_keys=True, separators=(",", ":")).encode("utf-8")

    output = Path(__file__).with_name("ecg-demo-alt.safetensors")
    with output.open("wb") as handle:
        handle.write(struct.pack("<Q", len(header_bytes)))
        handle.write(header_bytes)
        handle.write(payload)

    print(f"wrote {output} ({8 + len(header_bytes) + len(payload)} bytes)")


if __name__ == "__main__":
    main()
