# MduXEmbedBlobImpl.cmake
#
# The generation half of mdux_embed_blob(), run via `cmake -P` from a custom command so it re-runs
# when the input file changes. See MduXEmbedBlob.cmake for the rationale.
#
# Expected variables (passed with -D):
#   MDUX_BLOB_INPUT  - the binary file to embed
#   MDUX_BLOB_SYMBOL - the accessor name, already validated as a C++ identifier
#   MDUX_BLOB_SOURCE - the .cpp to write
#   MDUX_BLOB_HEADER - the .hpp to write

file(READ "${MDUX_BLOB_INPUT}" blob_hex HEX)
string(LENGTH "${blob_hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")

# Twelve bytes per line keeps the generated file diffable without making it enormous. It is never
# read by a human in practice, but a file nobody can open at all is worse.
set(body "")
set(index 0)
while(index LESS hex_length)
    string(SUBSTRING "${blob_hex}" ${index} 2 byte)
    string(APPEND body "0x${byte},")
    math(EXPR index "${index} + 2")
    math(EXPR position "${index} / 2")
    math(EXPR wrap "${position} % 12")
    if(wrap EQUAL 0)
        string(APPEND body "\n    ")
    else()
        string(APPEND body " ")
    endif()
endwhile()

get_filename_component(input_name "${MDUX_BLOB_INPUT}" NAME)

file(WRITE "${MDUX_BLOB_HEADER}"
"// Generated by mdux_embed_blob() from ${input_name}. Do not edit.
#pragma once

// Deliberately includes nothing.
//
// A consumer of this header reaches std::span and std::byte through `import std;`, and including
// <span> or <cstddef> in the same translation unit as that import is a hard error - the two
// declare the same entities by different routes ('redefinition of enum class std::byte' and a
// hundred lines like it). Declaring the accessor and letting the consumer supply the names is the
// arrangement that works from both a module-importing and an include-based translation unit.
//
// Include this after `import std;`.

/// The embedded contents of ${input_name}, ${byte_count} bytes, aligned for f32 access.
[[nodiscard]] std::span<const std::byte> ${MDUX_BLOB_SYMBOL}() noexcept;
")

file(WRITE "${MDUX_BLOB_SOURCE}"
"// Generated by mdux_embed_blob() from ${input_name}. Do not edit.
//
// A plain array in an ordinary translation unit, deliberately not constexpr and not a module: a
// multi-megabyte constexpr array takes minutes to compile and can exhaust MSVC.
//
// alignas(16) is load-bearing. Classifier1D::create() reads a weight blob as f32 and refuses one
// that is not suitably aligned, and a bare unsigned char array has alignment 1.
//
// An ordinary include-based translation unit, so the std headers come in the ordinary way here.
// The header itself includes nothing - see the comment in it for why.
#include <cstddef>
#include <span>

#include \"${MDUX_BLOB_SYMBOL}.hpp\"

namespace {

alignas(16) const unsigned char ${MDUX_BLOB_SYMBOL}Data[] = {
    ${body}
};

}  // namespace

std::span<const std::byte> ${MDUX_BLOB_SYMBOL}() noexcept {
    return std::span<const std::byte>{reinterpret_cast<const std::byte*>(${MDUX_BLOB_SYMBOL}Data),
                                      ${byte_count}};
}
")
