# Writes the MedUI Studio frontend into a C++17 source as a table of immutable byte arrays (#327).
#
# Invoked by tools/CMakeLists.txt with:
#   MDUX_STUDIO_FILES   "|"-separated absolute paths, served at "/" for index.html and "/<name>" otherwise
#   MDUX_STUDIO_OUTPUT  the source file to write
#
# The assets are compiled in rather than read at run time so that the service serves exactly the reviewed
# files from its own build, and never a path under the repository it was pointed at.

string(REPLACE "|" ";" files "${MDUX_STUDIO_FILES}")
set(arrays "")
set(entries "")
set(index 0)
foreach(file IN LISTS files)
    get_filename_component(name "${file}" NAME)
    get_filename_component(extension "${file}" LAST_EXT)
    if(extension STREQUAL ".html")
        set(type "text/html; charset=utf-8")
    elseif(extension STREQUAL ".css")
        set(type "text/css; charset=utf-8")
    elseif(extension STREQUAL ".js")
        set(type "text/javascript; charset=utf-8")
    else()
        message(FATAL_ERROR "MduXEmbedStudio: no content type for ${name}")
    endif()
    if(name STREQUAL "index.html")
        set(route "/")
    else()
        set(route "/${name}")
    endif()
    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" hexLength)
    math(EXPR size "${hexLength} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],)(0x[0-9a-f][0-9a-f],))" "\\1\n" bytes "${bytes}")
    string(APPEND arrays "const unsigned char asset${index}[] = {\n${bytes}0x00};\n")
    string(APPEND entries "    {\"${route}\", \"${type}\", asset${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${MDUX_STUDIO_OUTPUT}"
"// Generated by cmake/MduXEmbedStudio.cmake. Do not edit.
#include <cstddef>
#include \"StudioAssets.hpp\"
namespace mdux::tools::preview {
namespace {
${arrays}}  // namespace
const StudioAsset studioAssets[] = {
${entries}};
const std::size_t studioAssetCount = ${index};
}  // namespace mdux::tools::preview
")
